import ProductDetail from '../../components/ProductDetail';
import styles from '../../styles/Home.module.css';
import Head from 'next/head';
import ParticipantList from '../../components/ParticipantList';
import RoomInfo from '../../components/RoomInfo';
import axios from 'axios';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/dist/client/router';
import { getRoomById } from '../../services/giveaway';
import { useUser } from '../../context/user';

const Event = () => {
  const user = useUser();
  const router = useRouter();
  const { id } = router.query;
  const [data, setData] = useState([]);

  const fetchData = async () => {
    try {
      await getRoomById(id).then((data) => setData(data));
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    fetchData();
    console.log(data);
  }, []);
  return (
    <>
      <div className={styles.container + 'container'}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main + `top-0 p-6`}>
          <ProductDetail />
          <div className="flex flex-row w-full">
            <ParticipantList />
            <RoomInfo />
          </div>
        </main>
      </div>
    </>
  );
};

export async function getServerSideProps({ req, query }) {
  const user = await getUser(req);
  const response = await axios.get(
    `https://lepasaja-backend.herokuapp.com/api/v1/rooms/${id}`
  );
  console.log(response);
  const data = await response.data;
  return {
    props: {
      data: data,
    },
  };
}

export default Event;
