import React, { useEffect, useState } from 'react';

import Head from 'next/head';
import styles from '../styles/Home.module.css';
import NewGiveaway from '../components/NewGiveaway';
import ProductGiveaway from '../components/ProductGiveaway';
import ProductCategory from '../components/ProductCategory';
import Carousel from '../components/Carousel/Carousel';
import ImageCarousel from '../components/ImageCarousel';

export default function Home() {
  const imgArray = [
    <ImageCarousel src="/images/image1.jpg" />,
    <ImageCarousel src="/images/image2.jpg" />,
    <ImageCarousel src="/images/image3.jpg" />,
    <ImageCarousel src="/images/image4.jpg" />,
  ];

  const [category, setCategory] = useState(1);

  const getCategoryData = (childCategoryData) => {
    setCategory(childCategoryData);
  };

  useEffect(() => {
    console.log(category);
  }, [category]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Carousel imgArray={imgArray} />
        <NewGiveaway />
        <ProductCategory categoryDataFunc={getCategoryData} />
        <ProductGiveaway categoryIdFilter={category} />
      </main>
    </div>
  );
}
